# ffnet example XOR

Feed forward multi-layer perceptron demonstration program.

Given (a) the structure of a multilayer perceptron, (b) weight matrices (including bias), and (c) input data X, compute output Y

1) Data File: XOR Problem

In [8]:
import numpy as np
import pandas as pd

with open('Ex_FFnetData.csv', 'r', encoding='utf-8-sig') as f:
  X = np.genfromtxt(f, dtype='f4', delimiter=',')

(K,d) = np.shape(X)
(K, d)

(100, 2)

3) Evaluate the output of the xor problem. 

In [9]:
w1 = np.array([[1, -3, 4], [5, 2, -5],[-5, 5,-1]])   # first layer weights top row is the bias
w2 = np.array([[-2.5, 1 , 1, 1]]).T     # second layer weight. Frist element is the bias
print(w1)
print(w2)

[[ 1 -3  4]
 [ 5  2 -5]
 [-5  5 -1]]
[[-2.5]
 [ 1. ]
 [ 1. ]
 [ 1. ]]


In [11]:
from scipy.stats import logistic
hactivation = logistic.cdf(np.hstack((np.ones((K,1)), X)).dot(w1),1)
output1 = logistic.cdf(np.hstack((np.ones((K,1)), hactivation)).dot(w2),1)
print(hactivation)
print(output1)

[[0.5        0.01798621 0.95257413]
 [0.36457773 0.0309348  0.94729449]
 [0.24766587 0.05270501 0.94146322]
 [0.15887133 0.08839834 0.93503103]
 [0.09777456 0.14457501 0.92794615]
 [0.05853568 0.22754952 0.92015391]
 [0.03444464 0.33924739 0.91160005]
 [0.02005732 0.47225353 0.9022272 ]
 [0.01160725 0.6093189  0.89197833]
 [0.00669285 0.73105858 0.88079708]
 [0.63542227 0.02236192 0.92015464]
 [0.5        0.03833769 0.91160086]
 [0.36457773 0.06496836 0.90222809]
 [0.24766587 0.10801974 0.89197929]
 [0.15887133 0.17428181 0.88079813]
 [0.09777015 0.26894535 0.86862892]
 [0.05853567 0.39068593 0.85542252]
 [0.03444464 0.52775145 0.84113134]
 [0.02005732 0.66075715 0.82571531]
 [0.01160725 0.77245399 0.80914281]
 [0.75233413 0.02777205 0.86863006]
 [0.63542227 0.04742542 0.85542376]
 [0.5        0.07984463 0.84113267]
 [0.36457773 0.1313688  0.82571675]
 [0.24766587 0.20860413 0.80914435]
 [0.15886466 0.31480285 0.79139257]
 [0.09777014 0.44467499 0.77245574]
 [0.05853568 0.58257183 0.75