In [33]:
import numpy as np

with open('Amat.csv', 'r') as f:
  a = np.genfromtxt(f,delimiter=',')
a = tf.reshape(a, [1,7,6,1])
a = tf.cast(a, tf.float32)
print(a.shape)
b = tf.constant([[0,-1,0], [-1,4,-1], [0,-1,0]], dtype=tf.float32)
b = tf.reshape(b,[3,3,1,1])

(1, 7, 6, 1)


In [34]:
S = 2
P = 1

In [43]:
import tensorflow as tf
c = tf.nn.conv2d(a, b, strides=S, padding=[[0, 0], [P, P], [P, P], [0, 0]])
print(c)
print(tf.reshape(c, (4,3)))

tf.Tensor(
[[[[ 31.]
   [ 70.]
   [ 39.]]

  [[-99.]
   [-44.]
   [ 49.]]

  [[  2.]
   [-15.]
   [  9.]]

  [[-14.]
   [ 10.]
   [-34.]]]], shape=(1, 4, 3, 1), dtype=float32)
tf.Tensor(
[[ 31.  70.  39.]
 [-99. -44.  49.]
 [  2. -15.   9.]
 [-14.  10. -34.]], shape=(4, 3), dtype=float32)


In [45]:
a = tf.constant([[5,-1,7,6], [2,4,-2, 10], [11,-3,3, 11]], dtype=tf.float32)
a = tf.reshape(a, [1,3,4,1])
a = tf.cast(a, tf.float32)

b = tf.constant([[0,1,0], [1,4,1], [0,1,0]], dtype=tf.float32)
b = b * (1/8)
b = tf.reshape(b, [3,3,1,1])
b = tf.cast(b, tf.float32)
print(b)

tf.Tensor(
[[[[0.   ]]

  [[0.125]]

  [[0.   ]]]


 [[[0.125]]

  [[0.5  ]]

  [[0.125]]]


 [[[0.   ]]

  [[0.125]]

  [[0.   ]]]], shape=(3, 3, 1, 1), dtype=float32)


In [49]:
S = 2
P = 1
c = tf.nn.conv2d_transpose(a, b, (5,7), strides=S, padding=[[0, 0], [P, P], [P, P], [0, 0]])
print(c)
print(tf.reshape(c,(5,7)))

tf.Tensor(
[[[[ 2.5  ]
   [ 0.5  ]
   [-0.5  ]
   [ 0.75 ]
   [ 3.5  ]
   [ 1.625]
   [ 3.   ]]

  [[ 0.875]
   [ 0.   ]
   [ 0.375]
   [ 0.   ]
   [ 0.625]
   [ 0.   ]
   [ 2.   ]]

  [[ 1.   ]
   [ 0.75 ]
   [ 2.   ]
   [ 0.25 ]
   [-1.   ]
   [ 1.   ]
   [ 5.   ]]

  [[ 1.625]
   [ 0.   ]
   [ 0.125]
   [ 0.   ]
   [ 0.125]
   [ 0.   ]
   [ 2.625]]

  [[ 5.5  ]
   [ 1.   ]
   [-1.5  ]
   [ 0.   ]
   [ 1.5  ]
   [ 1.75 ]
   [ 5.5  ]]]], shape=(1, 5, 7, 1), dtype=float32)
tf.Tensor(
[[ 2.5    0.5   -0.5    0.75   3.5    1.625  3.   ]
 [ 0.875  0.     0.375  0.     0.625  0.     2.   ]
 [ 1.     0.75   2.     0.25  -1.     1.     5.   ]
 [ 1.625  0.     0.125  0.     0.125  0.     2.625]
 [ 5.5    1.    -1.5    0.     1.5    1.75   5.5  ]], shape=(5, 7), dtype=float32)
