In [105]:
# part of the code also refers to:
# https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/
# !pip install d2l==0.17.0
import tensorflow as tf
import numpy as np
#from google.colab import drive
from tensorflow import keras
from sklearn.model_selection import train_test_split

In [106]:
# import data
#drive.mount('/content/drive')
with open('iris.csv', 'r') as f: 
  data = np.genfromtxt(f, dtype='f4', delimiter=',')
X = data[:,:4]
# y = [data[:,4] == 1, data[:,4] == 2, data[:,4] == 3]
y = data[:,4]

In [107]:
# partition into training and validation set at 80/20 division
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
# Converting y_r and y_t into one-hot encoding using a keras utility
#  to_categorical
# The class vector to be converted into a matrix is assumed to contain
#  integers from 0 to num_classes. The label in iris.csv is 1, 2, 3
#  Hence we subtract it by 1 before conversion
y_train = keras.utils.to_categorical(y_train-1)
y_test = keras.utils.to_categorical(y_test-1)

In [108]:
# define the keras model
# 4-10-10-10-3 configuration, relu and softmax activation for the 
# hidden layer and output layer respectively
net = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, input_dim=4, activation = 'relu'),
    tf.keras.layers.Dense(3, activation = 'relu'),
    tf.keras.layers.Dense(3, activation = 'relu'),
    tf.keras.layers.Dense(3, activation = 'relu'),
    tf.keras.layers.Dense(3, activation = 'relu'),
    tf.keras.layers.Dense(3, activation = 'relu'),
    tf.keras.layers.Dense(3, activation = 'relu'),
    tf.keras.layers.Dense(3, activation = 'relu'),
    tf.keras.layers.Dense(3, activation = 'relu'),
    tf.keras.layers.Dense(3, activation='softmax')])

In [109]:
# compile the keras model
net.compile(loss='binary_crossentropy', optimizer='adam', 
              metrics=['accuracy'])

In [110]:
# fit the keras model on the dataset
net.fit(X_train, y_train, epochs=150, batch_size=10)

Epoch 1/150
12/12 [==============================] - 0s 860us/step - loss: 0.6874 - accuracy: 0.2667
Epoch 2/150
12/12 [==============================] - 0s 788us/step - loss: 0.6792 - accuracy: 0.3750
Epoch 3/150
12/12 [==============================] - 0s 857us/step - loss: 0.6703 - accuracy: 0.3750
Epoch 4/150
12/12 [==============================] - 0s 910us/step - loss: 0.6607 - accuracy: 0.3750
Epoch 5/150
12/12 [==============================] - 0s 962us/step - loss: 0.6513 - accuracy: 0.3750
Epoch 6/150
12/12 [==============================] - 0s 979us/step - loss: 0.6438 - accuracy: 0.3750
Epoch 7/150
12/12 [==============================] - 0s 946us/step - loss: 0.6401 - accuracy: 0.3750
Epoch 8/150
12/12 [==============================] - 0s 751us/step - loss: 0.6392 - accuracy: 0.3750
Epoch 9/150
12/12 [==============================] - 0s 761us/step - loss: 0.6386 - accuracy: 0.3750
Epoch 10/150
12/12 [==============================] - 0s 802us/step - loss: 0.6382 - accura

In [111]:
# Evaluate the trained model using keras built-in function
score = net.evaluate(X_test, y_test, verbose=0)
print("Test loss:", format(score[0],".4f"))
print("Test accuracy:", score[1])

Test loss: 0.4668
Test accuracy: 0.5666666626930237


In [112]:
# Evaluate predicted testing output
# Since softmax output is used, these outputs are probability 
# vectors of value between 0 and 1 and values of each output 
# vector added to 1
y_softmax = net.predict(X_test)
# y_pc gives the indices (strating from 0) of the max elements
y_pc = np.argmax(y_softmax, axis = -1)
# convert y_pc into one-hot encoding
y_pred = keras.utils.to_categorical(y_pc)

Cmat = tf.math.confusion_matrix(y_test.argmax(axis=-1),y_pred.argmax(axis=-1))
print(Cmat)

1/1 [==============================] - 0s 35ms/step
tf.Tensor(
[[ 5  0  0]
 [ 4  2  9]
 [ 0  0 10]], shape=(3, 3), dtype=int32)


In [113]:
#drive.flush_and_unmount()

In [114]:
#Observation: Not enough neurons and learning per layer, too low dimension?