In [1]:
# part of the code also refers to:
# https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/
# !pip install d2l==0.17.0
import tensorflow as tf
import numpy as np
#from google.colab import drive
from tensorflow import keras
from sklearn.model_selection import train_test_split

/Users/admin/GitHub/nn/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [2]:
# import data
#drive.mount('/content/drive')
with open('iris.csv', 'r') as f: 
  data = np.genfromtxt(f, dtype='f4', delimiter=',')
X = data[:,:4]
# y = [data[:,4] == 1, data[:,4] == 2, data[:,4] == 3]
y = data[:,4]

In [3]:
# partition into training and validation set at 80/20 division
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
# Converting y_r and y_t into one-hot encoding using a keras utility
#  to_categorical
# The class vector to be converted into a matrix is assumed to contain
#  integers from 0 to num_classes. The label in iris.csv is 1, 2, 3
#  Hence we subtract it by 1 before conversion
y_train = keras.utils.to_categorical(y_train-1)
y_test = keras.utils.to_categorical(y_test-1)

In [4]:
# define the keras model
# 4-10-10-10-3 configuration, relu and softmax activation for the 
# hidden layer and output layer respectively
net = tf.keras.models.Sequential([
    tf.keras.layers.Dense(3, input_dim=4, activation = 'relu'),
    tf.keras.layers.Dense(3, activation = 'relu'),
    tf.keras.layers.Dense(3, activation = 'relu'),
    tf.keras.layers.Dense(3, activation = 'relu'),
    tf.keras.layers.Dense(3, activation = 'relu'),
    tf.keras.layers.Dense(3, activation = 'relu'),
    tf.keras.layers.Dense(3, activation = 'relu'),
    tf.keras.layers.Dense(3, activation = 'relu'),
    tf.keras.layers.Dense(3, activation='softmax')])

In [5]:
# compile the keras model
net.compile(loss='binary_crossentropy', optimizer='adam', 
              metrics=['accuracy'])

In [6]:
# fit the keras model on the dataset
net.fit(X_train, y_train, epochs=150, batch_size=10)

Epoch 1/150
12/12 [==============================] - 0s 885us/step - loss: 0.9576 - accuracy: 0.3000
Epoch 2/150
12/12 [==============================] - 0s 700us/step - loss: 0.8677 - accuracy: 0.3000
Epoch 3/150
12/12 [==============================] - 0s 673us/step - loss: 0.8115 - accuracy: 0.3000
Epoch 4/150
12/12 [==============================] - 0s 911us/step - loss: 0.7742 - accuracy: 0.3000
Epoch 5/150
12/12 [==============================] - 0s 914us/step - loss: 0.7501 - accuracy: 0.3000
Epoch 6/150
12/12 [==============================] - 0s 777us/step - loss: 0.7360 - accuracy: 0.3000
Epoch 7/150
12/12 [==============================] - 0s 798us/step - loss: 0.7248 - accuracy: 0.3000
Epoch 8/150
12/12 [==============================] - 0s 971us/step - loss: 0.7181 - accuracy: 0.3000
Epoch 9/150
12/12 [==============================] - 0s 903us/step - loss: 0.7121 - accuracy: 0.3000
Epoch 10/150
12/12 [==============================] - 0s 816us/step - loss: 0.7078 - accura

In [7]:
# Evaluate the trained model using keras built-in function
score = net.evaluate(X_test, y_test, verbose=0)
print("Test loss:", format(score[0],".4f"))
print("Test accuracy:", score[1])

Test loss: 0.4129
Test accuracy: 0.7333333492279053


In [8]:
# Evaluate predicted testing output
# Since softmax output is used, these outputs are probability 
# vectors of value between 0 and 1 and values of each output 
# vector added to 1
y_softmax = net.predict(X_test)
# y_pc gives the indices (strating from 0) of the max elements
y_pc = np.argmax(y_softmax, axis = -1)
# convert y_pc into one-hot encoding
y_pred = keras.utils.to_categorical(y_pc)

Cmat = tf.math.confusion_matrix(y_test.argmax(axis=-1),y_pred.argmax(axis=-1))
print(Cmat)

1/1 [==============================] - 0s 46ms/step
tf.Tensor(
[[14  0  0]
 [ 0  0  8]
 [ 0  0  8]], shape=(3, 3), dtype=int32)


In [9]:
#drive.flush_and_unmount()

In [10]:
#Observation: Not enough neurons and learning per layer, too low dimension?