# ffnet example XOR

Feed forward multi-layer perceptron demonstration program.

Given (a) the structure of a multilayer perceptron, (b) weight matrices (including bias), and (c) input data X, compute output Y

1) Data File: XOR Problem

In [4]:
import numpy as np
X = [[0., 0.], [0., 1.], [1., 0.], [1., 1.]]
y = [0, 1, 1, 0]
(K,d) = np.shape(X)

3) Evaluate the output of the xor problem. 

In [5]:
w1 = np.array([[-0.5, -0.5], [1, -1],[-1, 1]])   # first layer weights top row is the bias
w2 = np.array([[-0.5, 1 , 1]]).T     # second layer weight. Frist element is the bias
print(w1)
print(w2)

[[-0.5 -0.5]
 [ 1.  -1. ]
 [-1.   1. ]]
[[-0.5]
 [ 1. ]
 [ 1. ]]


In [6]:

hactivation = np.heaviside(np.hstack((np.ones((K,1)), X)).dot(w1),1)
output1 = np.heaviside(np.hstack((np.ones((K,1)), hactivation)).dot(w2),1)
print(hactivation)
print(output1)

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [0. 0.]]
[[0.]
 [1.]
 [1.]
 [0.]]
