In [3]:
import numpy as np
import pandas as pd
import collections


with open('winequality-red.csv', 'r', encoding='utf-8-sig') as f:
  df = pd.read_csv(f)

data = df.to_numpy()

X = data[:, :-1]
y = data[:, -1]
#Print the shapes of X and y
print(X.shape)
print(y.shape)
#list all distinct class labels
print(np.unique(y))
# split X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)

(1599, 11)
(1599,)
[3. 4. 5. 6. 7. 8.]


In [4]:
from sklearn.linear_model import LogisticRegression
# Create an instance of Logistic Regression Classifier and fit the data.
logreg = LogisticRegression(multi_class='auto', max_iter=10000)
clf = logreg.fit(X_train, y_train)
print(y_train.shape)
print(X_train.shape)
#print(clf.coef_, clf.intercept_)

(1279,)
(1279, 11)


In [5]:
# Confusion matrix of the testing dataset
y_hat = clf.predict(X_test)
from sklearn.metrics import confusion_matrix

Cmat = confusion_matrix(y_test, y_hat)
acc = clf.score(X_test,y_test)

print("Confusion Matrix: ")
print(Cmat)
print("Accuracy: " + str(format(acc*100,'.3f')) + '%')

Confusion Matrix: 
[[  0   0   2   0   0   0]
 [  0   0   9   2   0   0]
 [  0   0 105  30   1   0]
 [  0   0  36  84   8   0]
 [  0   0   2  32   6   0]
 [  0   0   0   3   0   0]]
Accuracy: 60.938%


In [6]:
print(clf.predict_log_proba(X_test))

[[-5.07756683 -3.36291801 -0.7201979  -0.83579531 -3.28286719 -6.55367186]
 [-3.72411169 -3.58757521 -1.128523   -0.64719156 -2.32588331 -5.66120323]
 [-5.8308792  -3.58517798 -1.69804738 -0.50521909 -1.74614507 -4.77078852]
 ...
 [-4.7261708  -2.77420762 -0.43940825 -1.30343113 -4.42660463 -7.16937077]
 [-4.13108485 -3.23131612 -0.66947128 -0.90294985 -3.64126005 -7.06032826]
 [-3.11842695 -4.11490259 -0.69984425 -0.95225316 -2.89296413 -6.50176072]]


In [18]:
#args
print(y_test)
y_test_4 = np.array([1 if y == 4. else 0 for y in y_test])
print(y_test_4)

[5. 6. 6. 7. 6. 6. 5. 7. 6. 4. 6. 5. 5. 5. 3. 6. 6. 6. 6. 5. 5. 6. 6. 6.
 6. 4. 5. 6. 7. 5. 5. 7. 6. 6. 5. 6. 6. 6. 7. 5. 7. 5. 6. 6. 5. 5. 6. 5.
 7. 7. 6. 5. 6. 5. 6. 6. 5. 5. 4. 6. 5. 6. 5. 6. 6. 6. 6. 5. 6. 7. 7. 6.
 7. 5. 5. 5. 5. 5. 6. 6. 6. 5. 6. 6. 5. 5. 6. 5. 6. 5. 6. 5. 6. 4. 5. 6.
 6. 5. 6. 6. 6. 5. 5. 6. 5. 6. 6. 6. 6. 7. 5. 6. 6. 6. 8. 6. 5. 5. 6. 6.
 6. 5. 6. 7. 6. 7. 6. 7. 7. 5. 5. 5. 5. 6. 5. 6. 7. 7. 5. 6. 6. 4. 5. 5.
 5. 7. 6. 5. 6. 8. 6. 6. 5. 7. 5. 7. 5. 5. 5. 5. 5. 6. 5. 6. 5. 5. 5. 6.
 5. 6. 7. 6. 5. 7. 6. 5. 6. 5. 5. 5. 5. 6. 6. 5. 5. 6. 6. 7. 5. 5. 6. 6.
 5. 5. 5. 7. 6. 5. 5. 7. 4. 5. 6. 5. 6. 6. 6. 6. 5. 5. 6. 5. 7. 5. 6. 5.
 6. 5. 6. 5. 5. 7. 3. 6. 5. 5. 5. 5. 6. 8. 7. 5. 6. 6. 5. 6. 6. 4. 5. 5.
 5. 5. 6. 6. 5. 5. 6. 5. 6. 6. 6. 5. 7. 5. 6. 5. 5. 5. 7. 5. 6. 4. 6. 5.
 7. 4. 5. 7. 7. 7. 5. 7. 6. 6. 6. 5. 5. 6. 5. 5. 6. 5. 5. 7. 7. 5. 6. 6.
 5. 5. 5. 6. 5. 5. 5. 5. 6. 4. 6. 7. 6. 6. 7. 5. 5. 5. 5. 5. 5. 6. 5. 6.
 4. 6. 5. 6. 6. 5. 5. 6.]
[0 0 0 0 0 0 0 0 0 1 0 0 

In [1]:
import sklearn.metrics as metrics
probs = clf.predict_proba(X_test)
preds = probs[:,1]
fpr, tpr, threshold = metrics.roc_curve(y_test_4, preds)
roc_auc = metrics.auc(fpr, tpr)

import matplotlib.pyplot as plt
plt.plot(fpr,tpr,label="label: 4, auc="+str(roc_auc))
plt.legend(loc=4)
plt.show()


NameError: name 'clf' is not defined