In [2]:
import numpy as np

x = np.array( [[1,1,1,1,1,1,1,1,1,1 ],
             [0.84, 0.81, 0.92, 0.19, 0.61, 0.35, 0.58, 0.91, 0.75, 0.38], 
             [0.25, 0.24, 0.34, 0.25, 0.47, 0.83, 0.54, 0.28, 0.75, 0.56]])
y = np.array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0])
w = np.array([-1, 10, -11.25]).reshape((-1,1))
#a
z = x.T @ w
print(z)

[[ 4.5875]
 [ 4.4   ]
 [ 4.375 ]
 [-1.9125]
 [-0.1875]
 [-6.8375]
 [-1.275 ]
 [ 4.95  ]
 [-1.9375]
 [-3.5   ]]


In [3]:
import math
sigmoid = lambda v:  1 / (1 + math.exp(-v))
print("sigmoid\n", np.vectorize(sigmoid)(z))

sigmoid
 [[0.98992428]
 [0.98787157]
 [0.98756835]
 [0.12870025]
 [0.45326185]
 [0.00107163]
 [0.21840254]
 [0.99296641]
 [0.12592276]
 [0.02931223]]


In [4]:
print("tanh\n", np.tanh(z))

tanh
 [[ 0.99979283]
 [ 0.99969858]
 [ 0.99968313]
 [-0.95729489]
 [-0.1853332 ]
 [-0.9999977 ]
 [-0.85514703]
 [ 0.99989966]
 [-0.95933529]
 [-0.9981779 ]]


In [5]:
relu = lambda v: max(0,v)
print("ReLU\n", np.vectorize(relu)(z))

ReLU
 [[4.5875]
 [4.4   ]
 [4.375 ]
 [0.    ]
 [0.    ]
 [0.    ]
 [0.    ]
 [4.95  ]
 [0.    ]
 [0.    ]]


In [6]:
threshold = lambda v: 1 if v >= 0 else 0
print("threshold\n", np.vectorize(threshold)(z))

threshold
 [[1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]]


In [7]:
#b
w_est = np.array([[0.1], [0.2], [-0.3]])
z_pred = x.T @ w_est
print(z_pred)

[[ 0.193]
 [ 0.19 ]
 [ 0.182]
 [ 0.063]
 [ 0.081]
 [-0.079]
 [ 0.054]
 [ 0.198]
 [ 0.025]
 [ 0.008]]


In [8]:
def I():
    return np.linalg.norm(z-y)
    
def sigmoid_deriv(x):
    f = 1/(1+math.exp(-x))
    df = f * (1 - f)
    return df
    
def grad_i(w_est):
    s = np.zeros(shape=(10, 3))
    for i in range(10):
        s[i] = ((z[i] * y[i]) * ((sigmoid_deriv((w_est.T @ x)[0][i])) * x[:,i]))
    s1 = np.sum(s, axis=0)
    return s1

alpha = 0.1

#b
w_t1 = w - (alpha * grad_i(w_est)).reshape((-1,1))
#print(alpha * grad_i())
#print(w)
print(I())
print(w_t1)

39.24181841479825
[[ -1.45365854]
 [  9.60494113]
 [-11.37576353]]


In [9]:
w_k = np.array([[0.1], [0.2], [0.3]])
print(w.shape)
print(x.shape)
w_k_1 = w_k + (0.5*(0 - 1) * np.array([[0.0], [0.19], [0.25]]))
w_k_1


(3, 1)
(3, 10)


array([[0.1  ],
       [0.105],
       [0.175]])