In [2]:
import numpy as np

x = np.array( [[1,1,1,1,1,1,1,1,1,1 ],
             [0.84, 0.81, 0.92, 0.19, 0.61, 0.35, 0.58, 0.91, 0.75, 0.38], 
             [0.25, 0.24, 0.34, 0.25, 0.47, 0.83, 0.54, 0.28, 0.75, 0.56]])
y = np.array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0])
w = np.array([-1, 10, -11.25]).reshape((-1,1))

z = x.T @ w


In [3]:
import math
sigmoid = lambda v:  1 / (1 + math.exp(-v))
print("sigmoid\n", np.vectorize(sigmoid)(z))

sigmoid
 [[0.98992428]
 [0.98787157]
 [0.98756835]
 [0.12870025]
 [0.45326185]
 [0.00107163]
 [0.21840254]
 [0.99296641]
 [0.12592276]
 [0.02931223]]


In [4]:
print("tanh\n", np.tanh(z))

tanh
 [[ 0.99979283]
 [ 0.99969858]
 [ 0.99968313]
 [-0.95729489]
 [-0.1853332 ]
 [-0.9999977 ]
 [-0.85514703]
 [ 0.99989966]
 [-0.95933529]
 [-0.9981779 ]]


In [5]:
relu = lambda v: max(0,v)
print("ReLU\n", np.vectorize(relu)(z))

ReLU
 [[4.5875]
 [4.4   ]
 [4.375 ]
 [0.    ]
 [0.    ]
 [0.    ]
 [0.    ]
 [4.95  ]
 [0.    ]
 [0.    ]]


In [6]:
threshold = lambda v: 1 if v >= 0 else 0
print("threshold\n", np.vectorize(threshold)(z))

threshold
 [[1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]]


In [25]:
def I():
    return np.linalg.norm(z-y)
def grad_i():
    relu_derivative = lambda v: 0 if v < 0 else 1
    s = np.zeros(shape=(10, 3))
    for i in range(10):
        s[i] = ((z[i] * y[i]) * ((relu_derivative((w.T @ x)[0][i])) * x[:,i]))
    s1 = np.sum(s, axis=0)
    return s1

alpha = 0.1
w_t1 = w - (alpha * grad_i()).reshape((-1,1))
#print(alpha * grad_i())
#print(w)
print(w_t1)

[[ -2.83125  ]
 [  8.4053   ]
 [-11.7576375]]
