In [39]:
import numpy as np
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))

X = np.array([[1,0.92,0.34], [1,0.19,0.25], [1,0.61,0.47]])
y = np.array([[1],[0],[0]])
w = np.array([[-1],[5],[2]])
z = np.vectorize(sigmoid)(X @ w)
print(z)
e = z - y
print(e)
loss = 0.5 * np.linalg.norm(e)
print(loss)

[[0.98634634]
 [0.61063923]
 [0.95212031]]
[[-0.01365366]
 [ 0.61063923]
 [ 0.95212031]]
0.5655969813933606


In [40]:
#p = f'(u(k)), deriv of activation function applied to data
p = z * (1-z)
print(p)

#K = minibatch size
K = 3

grad = (1/K)*X.T@(e*p)
print(grad)

[[0.01346724]
 [0.23775896]
 [0.04558723]]
[[0.06280187]
 [0.01796424]
 [0.01887795]]


In [41]:
alpha = 0.1
w_new = w - alpha*grad
print(w_new)
z_new = np.vectorize(sigmoid)(X @ w_new)
print(z_new)
loss = 0.5 * np.linalg.norm(z_new - y)
print(loss)

[[-1.00628019]
 [ 4.99820358]
 [ 1.99811221]]
[[0.98623038]
 [0.60895138]
 [0.9517422 ]]
0.5649833196097985
