In [2]:
import tensorflow as tf
from tensorflow.keras.utils import to_categorical
from tensorflow import keras
from tensorflow.keras import layers
from keras.models import Sequential

import numpy as np
import random
from sklearn.model_selection import train_test_split

In [3]:
with open('iris.csv', 'r') as f:
  temp = np.genfromtxt(f, dtype='f4', delimiter=',')


In [4]:
# Data Prep
X = temp[:,0:-1]   # features
y = temp[:,-1]     # labels are in the last column

# partition into 80/20% training/testing datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, shuffle=True, random_state=3, stratify=y)

# to_categorical starts with 0. converting {1,2, 3} to {0, 1, 2}
y_train = to_categorical(y_train-1)
y_test = to_categorical(y_test-1)
print('Shape of training features: ', X_train.shape)
print('Shape of training labels: ', y_train.shape)
print('Shape of testing features: ', X_test.shape)
print('Shape of testing labels: ', y_test.shape)

Shape of training features:  (120, 4)
Shape of training labels:  (120, 3)
Shape of testing features:  (30, 4)
Shape of testing labels:  (30, 3)


In [5]:
from keras.models import Sequential
from keras.layers import Activation,Dense
# NOTE: you can play around with normalization before or after ReLU activation
net = Sequential()
# Only one dense layer, with softmax activation
net.add(Dense(3, input_shape=(4,), activation='softmax'))

In [6]:
# Hyperparameters
batch_size = 10
lr = 0.03 # learning rate
num_epochs = 50

In [7]:
# compile and fit the keras model
opt = tf.keras.optimizers.SGD(learning_rate=lr)
net.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])

In [8]:
score = net.evaluate(X_test, y_test, verbose=1)
print("Test loss:", np.round(score[0],3))
print("Test accuracy:", np.round(score[1],3))

1/1 [==============================] - 0s 115ms/step - loss: 2.3519 - accuracy: 0.3000
Test loss: 2.352
Test accuracy: 0.3


In [9]:
net.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15 (60.00 Byte)
Trainable params: 15 (60.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [10]:
# Training
history = net.fit(X_train, y_train, epochs=num_epochs)

Epoch 1/50
4/4 [==============================] - 0s 962us/step - loss: 1.7025 - accuracy: 0.3250
Epoch 2/50
4/4 [==============================] - 0s 861us/step - loss: 1.0419 - accuracy: 0.3583
Epoch 3/50
4/4 [==============================] - 0s 913us/step - loss: 0.9370 - accuracy: 0.4917
Epoch 4/50
4/4 [==============================] - 0s 940us/step - loss: 0.8765 - accuracy: 0.5583
Epoch 5/50
4/4 [==============================] - 0s 1ms/step - loss: 0.8523 - accuracy: 0.5750
Epoch 6/50
4/4 [==============================] - 0s 1ms/step - loss: 0.7913 - accuracy: 0.7000
Epoch 7/50
4/4 [==============================] - 0s 1ms/step - loss: 0.7716 - accuracy: 0.6083
Epoch 8/50
4/4 [==============================] - 0s 1ms/step - loss: 0.7275 - accuracy: 0.6667
Epoch 9/50
4/4 [==============================] - 0s 1ms/step - loss: 0.7138 - accuracy: 0.6917
Epoch 10/50
4/4 [==============================] - 0s 1ms/step - loss: 0.6956 - accuracy: 0.6917
Epoch 11/50
4/4 [==============

In [11]:
# Performance Evaluation
from sklearn.metrics import confusion_matrix, accuracy_score
# y_pred is the softmax output that is posterior prob for each class/sample
y_pred = net.predict(X_test)
# convert to one-hot encoded format
y_pred_1hot =  np.argmax(y_pred, axis=1)
y_test_1hot = np.argmax(y_test, axis =1)
Cmat = confusion_matrix(y_test_1hot,y_pred_1hot)
Accuracy = round(100*np.sum(np.matrix.diagonal(Cmat))/np.sum(Cmat),2)
print("Confusion matrix:")
print(Cmat)
print("\nAccuracy = ", Accuracy, '%')

1/1 [==============================] - 0s 28ms/step
Confusion matrix:
[[10  0  0]
 [ 0  5  5]
 [ 0  0 10]]

Accuracy =  83.33 %
