In [1]:
# part of the code also refers to:
# https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/
# !pip install d2l==0.17.0
import tensorflow as tf
import numpy as np
#from google.colab import drive
from tensorflow import keras


/Users/admin/GitHub/nn/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [2]:
import keras
from keras import layers

# This is the size of our encoded representations
encoding_dim = 8  # 32 floats -> compression of factor 24.5, assuming the input is 784 floats

# This is our input image
input_img = keras.Input(shape=(8,))
# "encoded" is the encoded representation of the input
encoded = layers.Dense(encoding_dim, activation='relu')(input_img)
# "decoded" is the lossy reconstruction of the input
decoded = layers.Dense(8, activation='sigmoid')(encoded)

# This model maps an input to its reconstruction
autoencoder = keras.Model(input_img, decoded)

# This model maps an input to its encoded representation
encoder = keras.Model(input_img, encoded)

In [3]:
# This is our encoded (32-dimensional) input
encoded_input = keras.Input(shape=(encoding_dim,))
# Retrieve the last layer of the autoencoder model
decoder_layer = autoencoder.layers[-1]
# Create the decoder model
decoder = keras.Model(encoded_input, decoder_layer(encoded_input))
# configure the model to use a per-pixel binary crossentropy loss, and the Adam optimizer:
autoencoder.compile(optimizer='adam', loss='binary_crossentropy')
autoencoder.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 8)]               0         
                                                                 
 dense (Dense)               (None, 8)                 72        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
Total params: 144 (576.00 Byte)
Trainable params: 144 (576.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [4]:
from sklearn.preprocessing import OneHotEncoder

y = np.array([[1,2,3,4,5,6,7,8]])

y = y.reshape((-1,1))
print(y.shape)
enc = OneHotEncoder()
enc.fit(y)
#print(enc.transform(y).toarray())
y_enc = enc.transform(y).toarray()
print(y_enc.shape)
print(y_enc)
y_enc = y_enc.reshape((len(y_enc), np.prod(y_enc.shape[1:])))
print(y_enc)
print(y_enc.shape)

(8, 1)
(8, 8)
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
(8, 8)


In [5]:
# Train for 100 epochs
tf.config.run_functions_eagerly(True)
autoencoder.fit(y_enc, y_enc,
                epochs=2000,
                batch_size=8,
                shuffle=True, 
                validation_data=(y_enc, y_enc))

Epoch 1/2000
1/1 [==============================] - 0s 51ms/step - loss: 0.7588 - val_loss: 0.7573
Epoch 2/2000
1/1 [==============================] - 0s 17ms/step - loss: 0.7573 - val_loss: 0.7558
Epoch 3/2000
1/1 [==============================] - 0s 19ms/step - loss: 0.7558 - val_loss: 0.7544
Epoch 4/2000
1/1 [==============================] - 0s 19ms/step - loss: 0.7544 - val_loss: 0.7530
Epoch 5/2000
1/1 [==============================] - 0s 19ms/step - loss: 0.7530 - val_loss: 0.7515
Epoch 6/2000
1/1 [==============================] - 0s 18ms/step - loss: 0.7515 - val_loss: 0.7501
Epoch 7/2000
1/1 [==============================] - 0s 19ms/step - loss: 0.7501 - val_loss: 0.7487
Epoch 8/2000
1/1 [==============================] - ETA: 0s - loss: 0.7487

/Users/admin/GitHub/nn/.venv/lib/python3.9/site-packages/tensorflow/python/data/ops/structured_function.py:258: UserWarning: Even though the `tf.config.experimental_run_functions_eagerly` option is set, this option does not apply to tf.data functions. To force eager execution of tf.data functions, please use `tf.data.experimental.enable_debug_mode()`.
  warnings.warn(


1/1 [==============================] - 0s 18ms/step - loss: 0.7487 - val_loss: 0.7473
Epoch 9/2000
1/1 [==============================] - 0s 17ms/step - loss: 0.7473 - val_loss: 0.7458
Epoch 10/2000
1/1 [==============================] - 0s 17ms/step - loss: 0.7458 - val_loss: 0.7445
Epoch 11/2000
1/1 [==============================] - 0s 18ms/step - loss: 0.7445 - val_loss: 0.7431
Epoch 12/2000
1/1 [==============================] - 0s 19ms/step - loss: 0.7431 - val_loss: 0.7417
Epoch 13/2000
1/1 [==============================] - 0s 18ms/step - loss: 0.7417 - val_loss: 0.7403
Epoch 14/2000
1/1 [==============================] - 0s 18ms/step - loss: 0.7403 - val_loss: 0.7389
Epoch 15/2000
1/1 [==============================] - 0s 18ms/step - loss: 0.7389 - val_loss: 0.7376
Epoch 16/2000
1/1 [==============================] - 0s 18ms/step - loss: 0.7376 - val_loss: 0.7362
Epoch 17/2000
1/1 [==============================] - 0s 18ms/step - loss: 0.7362 - val_loss: 0.7349
Epoch 18/2000
1

In [12]:
encoder.predict(y_enc)

1/1 [==============================] - 0s 12ms/step


array([[1.7738979e+00, 2.8891261e+00, 2.1696091e-05, 1.5227908e-01,
        3.8292369e-01, 4.4307116e-01, 1.9819779e+00, 2.4111054e+00],
       [2.6903076e+00, 2.7081556e+00, 4.8427266e-01, 0.0000000e+00,
        0.0000000e+00, 9.2699850e-01, 0.0000000e+00, 3.5881996e-05],
       [1.4269849e+00, 1.7297333e-01, 0.0000000e+00, 1.4341745e+00,
        2.2579188e+00, 0.0000000e+00, 0.0000000e+00, 3.0624206e+00],
       [7.0198059e-01, 2.4593871e+00, 2.3407500e+00, 2.2092452e+00,
        1.0718131e-01, 3.6656857e-05, 8.0046982e-02, 1.6330395e+00],
       [2.7215264e+00, 0.0000000e+00, 0.0000000e+00, 1.1927569e-01,
        0.0000000e+00, 0.0000000e+00, 6.7165589e-01, 1.3798312e+00],
       [1.9587650e+00, 3.2625383e-01, 1.6942849e+00, 1.1414212e+00,
        6.0608941e-01, 1.8980724e+00, 1.8516644e+00, 7.8556538e-02],
       [3.4280914e-01, 4.4964147e-01, 1.0343939e-02, 2.9651153e+00,
        1.7350912e-04, 2.2502759e+00, 0.0000000e+00, 2.1481190e+00],
       [1.2151617e+00, 1.9420911e+00, 0.0