In [1]:
import numpy as np

from google.colab import drive
drive.mount('/content/drive')
# Load the data

with open('/content/drive/My Drive/Colab Notebooks/539/data/mnist_train-1.csv', 'r') as f:
  temp = np.genfromtxt(f,delimiter=',')
  X_train = temp[:,1:]
  y_train = temp[:,0].reshape((-1,1))

with open('/content/drive/My Drive/Colab Notebooks/539/data/mnist_test-1.csv', 'r') as f:
  temp = np.genfromtxt(f,delimiter=',')
  X_test = temp[:,1:]
  y_test = temp[:,0].reshape((-1,1))

Mounted at /content/drive


In [2]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential()
model.add(Dense(350, activation='ReLU'))
model.add(Dense(50, activation='ReLU'))
#output layer
model.add(Dense(10, activation='softmax'))

In [3]:
from tensorflow.keras.utils import to_categorical
Y_train = to_categorical(y_train)
Y_test = to_categorical(y_test)

In [4]:
#print(X_train.shape)
#print(Y_train.shape)
#print(Y_train[:20])
#print(y_train[:20])

In [7]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, Y_train, epochs=10, batch_size=32, verbose=1)

Epoch 1/10
1875/1875 [==============================] - 12s 6ms/step - loss: 0.1326 - accuracy: 0.9702
Epoch 2/10
1875/1875 [==============================] - 11s 6ms/step - loss: 0.1047 - accuracy: 0.9744
Epoch 3/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0960 - accuracy: 0.9771
Epoch 4/10
1875/1875 [==============================] - 12s 6ms/step - loss: 0.0934 - accuracy: 0.9779
Epoch 5/10
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0763 - accuracy: 0.9816
Epoch 6/10
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0711 - accuracy: 0.9829
Epoch 7/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0771 - accuracy: 0.9823
Epoch 8/10
1875/1875 [==============================] - 10s 6ms/step - loss: 0.0707 - accuracy: 0.9849
Epoch 9/10
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0648 - accuracy: 0.9856
Epoch 10/10
1875/1875 [==============================] - 11s 6ms/step - l

In [8]:
test_results = model.evaluate(X_test, Y_test, verbose=1)
print(f'Test results - Loss: {test_results[0]} - Accuracy: {test_results[1]}%')

313/313 [==============================] - 1s 2ms/step - loss: 0.2017 - accuracy: 0.9715
Test results - Loss: 0.20167230069637299 - Accuracy: 0.9714999794960022%


In [10]:
from sklearn.metrics import confusion_matrix

y_pred_weights = model.predict(X_test)
y_pred = np.argmax(y_pred_weights, axis=1)

print(confusion_matrix(y_test, y_pred))


313/313 [==============================] - 1s 2ms/step
[[ 972    0    1    0    1    1    1    1    2    1]
 [   0 1121    1    1    1    1    2    2    6    0]
 [   6    2  993    4   11    0    2    8    6    0]
 [   0    1   20  964    0   13    0    6    5    1]
 [   1    0    0    0  964    0    6    3    2    6]
 [   3    3    0   11    2  850   12    1    8    2]
 [   6    2    0    0    2    0  946    0    2    0]
 [   1    2    3    0    0    0    0 1015    2    5]
 [  15    0    5    1   10    4    5    3  923    8]
 [   3    4    1    7   11    1    0   13    2  967]]
