In [3]:
import numpy as np
import tensorflow as tf

A = tf.constant([[9,4,7,1,5], 
              [7,3,7,7,0], 
              [3,10,10,2,8],
              [2,5,7,1,6]], dtype=tf.float32)
A = tf.reshape(A, [1,4,5,1])
B = tf.constant([[0,-1,0],
              [-1,4,-1],
              [0,-1,0]], dtype=tf.float32)
B = tf.reshape(B, [3,3,1,1])

In [5]:
c = tf.nn.conv2d(A, B, strides=1, padding="SAME")
print(c)

tf.Tensor(
[[[[ 25.]
   [ -3.]
   [ 16.]
   [-15.]
   [ 19.]]

  [[ 13.]
   [-16.]
   [  1.]
   [ 18.]
   [-20.]]

  [[ -7.]
   [ 19.]
   [ 14.]
   [-18.]
   [ 24.]]

  [[  0.]
   [  1.]
   [ 12.]
   [-11.]
   [ 15.]]]], shape=(1, 4, 5, 1), dtype=float32)


In [18]:
S = 2
P = 1
c = tf.nn.conv2d_transpose(A, B, (8,10), strides=S, padding=[[0, 0], [P, P], [P, P], [0, 0]])
print(tf.reshape(c,(8,10)))

tf.Tensor(
[[ 36. -13.  16. -11.  28.  -8.   4.  -6.  20.  -5.]
 [-16.   0.  -7.   0. -14.   0.  -8.   0.  -5.   0.]
 [ 28. -10.  12. -10.  28. -14.  28.  -7.   0.   0.]
 [-10.   0. -13.   0. -17.   0.  -9.   0.  -8.   0.]
 [ 12. -13.  40. -20.  40. -12.   8. -10.  32.  -8.]
 [ -5.   0. -15.   0. -17.   0.  -3.   0. -14.   0.]
 [  8.  -7.  20. -12.  28.  -8.   4.  -7.  24.  -6.]
 [ -2.   0.  -5.   0.  -7.   0.  -1.   0.  -6.   0.]], shape=(8, 10), dtype=float32)
