In [1]:
## Breast Cancer LASSO Exploration
## Prepare workspace
from scipy.io import loadmat
import numpy as np
X = loadmat("BreastCancer.mat")['X']
y = loadmat("BreastCancer.mat")['y']

##  10-fold CV 

# each row of setindices denotes the starting an ending index for one
# partition of the data: 5 sets of 30 samples and 5 sets of 29 samples
setindices = [[1,30],[31,60],[61,90],[91,120],[121,150],[151,179],[180,208],[209,237],[238,266],[267,295]]

# each row of holdoutindices denotes the partitions that are held out from
# the training set
holdoutindices = [[1,2],[2,3],[3,4],[4,5],[5,6],[7,8],[9,10],[10,1]]

cases = len(holdoutindices)

# be sure to initiate the quantities you want to measure before looping
# through the various training, validation, and test partitions

FileNotFoundError: [Errno 2] No such file or directory: 'BreastCancer.mat'

In [3]:
def ista_solve_hot( A, d, la_array ):
    # ista_solve_hot: Iterative soft-thresholding for multiple values of
    # lambda with hot start for each case - the converged value for the previous
    # value of lambda is used as an initial condition for the current lambda.
    # this function solves the minimization problem
    # Minimize |Ax-d|_2^2 + lambda*|x|_1 (Lasso regression)
    # using iterative soft-thresholding.
    max_iter = 10**4
    tol = 10**(-3)
    tau = 1/np.linalg.norm(A,2)**2
    n = A.shape[1]
    w = np.zeros((n,1))
    num_lam = len(la_array)
    X = np.zeros((n, num_lam))
    for i, each_lambda in enumerate(la_array):
        for j in range(max_iter):
            z = w - tau*(A.T@(A@w-d))
            w_old = w
            w = np.sign(z) * np.clip(np.abs(z)-tau*each_lambda/2, 0, np.inf)
            X[:, i:i+1] = w
            if np.linalg.norm(w - w_old) < tol:
                break
    return X

In [6]:
def ridge_regression(A, d, lam_arr):
    weights = np.zeros((A.shape[1], len(lam_arr)))
    for i, each_lambda in enumerate(lam_arr):
        
        diag = np.diag(np.full(A.shape[0],each_lambda))
        print(d.shape)
        print((A.T @ np.linalg.inv((A@A.T) + diag)).shape)
        w = (A.T @ np.linalg.inv((A@A.T) + diag)) @ d
        print(w)
        
    return 

In [ ]:
## 10-fold CV
lam_vals = np.logspace(-6,np.log10(20),num=100)
# each row of setindices denotes the starting an ending index for one
# partition of the data: 5 sets of 30 samples and 5 sets of 29 samples
setindices =[[1,30],[31,60],[61,90],[91,120],[121,150],[151,179],[180,208],[209,237],[238,266],[267,295]]
# each row of holdoutindices denotes the partitions that are held out from
# the training set
#holdoutindices = [[1,2],[2,3],[3,4],[4,5],[5,6],[6,7],[7,8],[8,9],[9,10],[10,1]]
#cases = len(holdoutindices)
# be sure to initiate the quantities you want to measure before looping
# through the various training, validation, and test partitions
# Loop over various cases

for k in range(2): #Set to 10 AT END
    for j in range(2): #Set to 10 AT END
        if k!=j:
            v1_ind = np.arange(setindices[k][0]-1,setindices[k][1])
            v2_ind = np.arange(setindices[j][0]-1,setindices[j][1])
            trn_ind = list(set(range(295))-set(v1_ind)-set(v2_ind))
            
            # define matrix of features and labels corresponding to first
            # validation set
            Av1 = X[v1_ind,:]
            bv1 = y[v1_ind]
            # define matrix of features and labels corresponding to second
            # validation set
            Av2 = X[v2_ind,:]
            bv2 = y[v2_ind]
            # define matrix of features and labels corresponding to the
            # training set
            At = X[trn_ind,:]
            bt = y[trn_ind]

            lasso_weights = ista_solve_hot(At,bt,lam_vals)
            ridge_weights = ridge_regression(At,bt,lam_vals)

    
# Use training data to learn classifier
#   
#
# Find best lambda value using first validation set, then evaluate
# performance on second validation set, and accumulate performance metrics
# over all cases partitions

(235, 1)
(8141, 235)
[[-0.00256096]
 [ 0.00445821]
 [ 0.00529461]
 ...
 [-0.01404949]
 [-0.00678241]
 [-0.0039963 ]]
(235, 1)
(8141, 235)
[[-0.00256096]
 [ 0.00445821]
 [ 0.00529461]
 ...
 [-0.01404949]
 [-0.00678241]
 [-0.0039963 ]]
(235, 1)
(8141, 235)
[[-0.00256096]
 [ 0.00445821]
 [ 0.00529461]
 ...
 [-0.01404949]
 [-0.00678241]
 [-0.0039963 ]]
(235, 1)
(8141, 235)
[[-0.00256096]
 [ 0.00445821]
 [ 0.00529461]
 ...
 [-0.01404949]
 [-0.00678241]
 [-0.0039963 ]]
(235, 1)
(8141, 235)
[[-0.00256096]
 [ 0.00445821]
 [ 0.00529461]
 ...
 [-0.01404949]
 [-0.00678241]
 [-0.0039963 ]]
(235, 1)
(8141, 235)
[[-0.00256096]
 [ 0.00445821]
 [ 0.00529461]
 ...
 [-0.01404949]
 [-0.00678241]
 [-0.0039963 ]]
(235, 1)
(8141, 235)
[[-0.00256096]
 [ 0.00445821]
 [ 0.00529461]
 ...
 [-0.01404949]
 [-0.00678241]
 [-0.0039963 ]]
(235, 1)
(8141, 235)
[[-0.00256096]
 [ 0.00445821]
 [ 0.00529461]
 ...
 [-0.01404949]
 [-0.00678241]
 [-0.0039963 ]]
(235, 1)
(8141, 235)
[[-0.00256096]
 [ 0.00445821]
 [ 0.00529461