# Train Ensemble of Bagged Classification Trees

Load Fisher's Iris Dataset.

In [1]:
import numpy as np
from google.colab import drive

drive.mount('/content/drive')

with open('/content/drive/My Drive/Colab Notebooks/data/iris.csv', 'r') as f:
    tmp = np.genfromtxt(f, dtype='f4', delimiter=',')

X = tmp[:,0:4]
Y = tmp[:,4]


Mounted at /content/drive


Partition the data into Training and Testing (7:3 split)

In [2]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.30, random_state=42)

print(X_train.shape)
print(X_test.shape)

(105, 4)
(45, 4)


Train a random forest classifier using the training data set. Use up to 20 estimators. Choose parameters using cross validation and paramter grid search

In [19]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
# initialize the model
clf = RandomForestClassifier(oob_score=True)
# setting up parameter grid search
param_grid = {'n_estimators': [5, 10, 15, 20]}
grid_clf = GridSearchCV(clf, param_grid, cv=5)
grid_clf.fit(X_train, y_train)
# the grid search yields a best model using CV
print(grid_clf.best_estimator_)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:583: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:583: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:583: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:583: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:583: UserWarning: Some inputs do not have OOB scores. This probably means too fe

RandomForestClassifier(n_estimators=5, oob_score=True)


/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:583: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(


Predict output on testing dataset using the best model after grid search and analyze the results.

In [20]:
from sklearn.metrics import confusion_matrix

y_hat = grid_clf.predict(X_test)
Cmat = confusion_matrix(y_test, y_hat)
acc = grid_clf.score(X_test,y_test)

print("Confusion Matrix: \n")
print(Cmat)
print("\n Accuracy: " + str(format(acc*100,'.2f')) + '%')

Confusion Matrix: 

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

 Accuracy: 100.00%
