In [10]:
import numpy as np


In [11]:
X = np.array([[1,2], [2,-1], [3,0]])
W_1 = np.array([[0.1, -0.1], [0.2,0], [0,0.3]])
W_2 = np.array([[0.05], [-0.1], [0.2]])
y = np.array([[0], [1], [0]])

In [12]:
import math
def sigmoid(x):
  return 1 / (1 + math.exp(-x))

In [17]:
Z_0 = X
U_1 = np.hstack((np.ones((3,1)), Z_0)) @ W_1
print(U_1)

Z_1 = np.vectorize(sigmoid)(U_1)
print(Z_1)

U_2 = np.hstack((np.ones((3,1)), Z_1)) @ W_2
print(U_2)

Z_2 = np.vectorize(sigmoid)(U_2)
print(Z_2)

[[ 0.3  0.5]
 [ 0.5 -0.4]
 [ 0.7 -0.1]]
[[0.57444252 0.62245933]
 [0.62245933 0.40131234]
 [0.66818777 0.47502081]]
[[0.11704761]
 [0.06801653]
 [0.07818539]]
[[0.52922854]
 [0.51699758]
 [0.5195364 ]]


In [28]:
def sigmoid_deriv(x):
    return sigmoid(x) * (1 - sigmoid(x))
sigma_2 = np.vectorize(sigmoid_deriv)(U_2) * (Z_2 - y)
print(sigma_2)

sigma_1 = sigma_2 @ W_2[1:, :].T
print(sigma_1)

[[ 0.13185501]
 [-0.12061106]
 [ 0.12968581]]
[[-0.0131855   0.026371  ]
 [ 0.01206111 -0.02412221]
 [-0.01296858  0.02593716]]


In [32]:
alpha = 0.05
W_2_grad = np.hstack((np.ones((3,1)), Z_1)).T @ sigma_2
W_2_new = W_2 - (alpha * W_2_grad)
print(W_2_grad)
print(W_2_new)

W_1_grad = np.hstack((np.ones((3,1)), Z_0)).T @ sigma_1
W_1_new = W_1 - (alpha * W_1_grad)
print(W_1_grad)
print(W_1_new)

[[0.14092976]
 [0.08732212]
 [0.09527513]]
[[ 0.04295351]
 [-0.10436611]
 [ 0.19523624]]
[[-0.01409298  0.02818595]
 [-0.02796903  0.05593806]
 [-0.03843211  0.07686422]]
[[ 0.10070465 -0.1014093 ]
 [ 0.20139845 -0.0027969 ]
 [ 0.00192161  0.29615679]]
